# Generated by Django 3.2.7 on 2021-09-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sommet',
            name='ville',
        ),
        migrations.AddField(
            model_name='rue',
            name='ville',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dijk.ville'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sommet',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sommet',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ville_of_Sommet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sommet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.sommet')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.ville')),
            ],
        ),
    ]
