# Generated by Django 3.2.7 on 2021-09-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('nom_norm', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('nom_norm', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sommet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_osm', models.IntegerField()),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Nœud_of_Rue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nœud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.sommet')),
                ('rue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.rue')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Cache_Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=200)),
                ('nœud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.sommet')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Arête',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longueur', models.FloatField()),
                ('cycla', models.FloatField(default=1.0)),
                ('arrivée', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sommet_arrivée', to='dijk.sommet')),
                ('départ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sommet_départ', to='dijk.sommet')),
                ('rue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.rue')),
            ],
        ),
    ]
