# Generated by Django 3.2.7 on 2022-02-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemin_d',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dijk.zone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sommet',
            name='id_osm',
            field=models.BigIntegerField(unique=True),
        ),
    ]
