# Generated by Django 3.2.7 on 2021-11-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0002_auto_20210902_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='rue',
            name='nœuds',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
