# Generated by Django 3.2.7 on 2022-02-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0002_auto_20220203_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='ville',
            name='code_insee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ville',
            name='densité',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ville',
            name='population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
