# Generated by Django 3.2.7 on 2022-02-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0003_auto_20220211_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='ville',
            name='géom_texte',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
