# Generated by Django 3.2.10 on 2021-12-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0004_rename_nœuds_rue_nœuds_à_découper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arête',
            name='rue',
        ),
        migrations.AddField(
            model_name='arête',
            name='rue',
            field=models.ManyToManyField(to='dijk.Rue'),
        ),
    ]
