# Generated by Django 3.2.7 on 2022-02-11 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0004_auto_20220211_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville_Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville1', to='dijk.ville')),
                ('ville2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville2', to='dijk.ville')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ville_ville',
            constraint=models.UniqueConstraint(fields=('ville1', 'ville2'), name='Pas de relation ville_ville en double.'),
        ),
    ]
