# Generated by Django 3.2.7 on 2022-02-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0005_auto_20220211_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='ville',
            name='données_présentes',
            field=models.BooleanField(default=False),
        ),
    ]
