# Generated by Django 3.2.10 on 2021-12-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0005_auto_20211225_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ville_of_sommet',
            name='sommet',
        ),
        migrations.RemoveField(
            model_name='ville_of_sommet',
            name='ville',
        ),
        migrations.AddField(
            model_name='arête',
            name='geom',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rue',
            name='nœuds_à_découper',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Nœud_of_Rue',
        ),
        migrations.DeleteModel(
            name='Ville_of_Sommet',
        ),
    ]
