# Generated by Django 3.2.10 on 2021-12-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0006_auto_20211228_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='arête',
            name='nom',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
