# Generated by Django 3.2.10 on 2021-12-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0007_arête_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='arête',
            name='cycla_défaut',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='arête',
            name='cycla',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
