# Generated by Django 3.2.10 on 2021-12-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0008_auto_20211229_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sommet',
            name='id_osm',
            field=models.IntegerField(unique=True),
        ),
    ]
