# Generated by Django 3.2.10 on 2021-12-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0009_alter_sommet_id_osm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cache_adresse',
            name='nœud',
        ),
        migrations.RemoveField(
            model_name='cache_adresse',
            name='ville',
        ),
        migrations.AddField(
            model_name='cache_adresse',
            name='nœuds_à_découper',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
