# Generated by Django 3.2.10 on 2021-12-31 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0010_auto_20211230_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemin_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar', models.BooleanField(default=False)),
                ('p_détour', models.FloatField()),
                ('étapes_texte', models.TextField()),
                ('interdites_texte', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ville_défaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.ville')),
            ],
        ),
        migrations.AddField(
            model_name='arête',
            name='zone',
            field=models.ManyToManyField(to='dijk.Zone'),
        ),
        migrations.AddField(
            model_name='sommet',
            name='zone',
            field=models.ManyToManyField(to='dijk.Zone'),
        ),
    ]
