# Generated by Django 3.2.7 on 2021-09-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arête',
            name='longueur',
            field=models.FloatField(default=1.5),
            preserve_default=False,
        ),
    ]
